### ISSUE TITLE
Which versions of ligo.skymap and python-ligo-lw should be used?

### ISSUE THREAD

**Issue by DanielWarshofsky** [nasa/dorado-scheduling#85]
When trying to import `from dorado.scheduling import skygrid` I get the error  `ImportError: cannot import name 'IDTypes' from 'ligo.lw.types'`. I installed the package using `pip install git+https://github.com/nasa/dorado-scheduling` as recommended on the [documentation page](https://dorado-scheduling.readthedocs.io/en/latest/quickstart.html). I've looked at `ligo.lw.types` and it looks like `IDTypes` was removed from the file during [v1.8](https://git.ligo.org/kipp.cannon/python-ligo-lw/-/commit/a292464f1c4742548432b2b0ac635dcc86ac82e1#0166038c341724e7d3c9f4ad6dda228d8b7fa902). Additionally the ligo.skymap package updated in [v0.61](https://github.com/lpsinger/ligo.skymap/commit/c7e5efdbd53a0a884f21ae281e76a39ba894eb6d) to account for this. When using `pip install git+https://github.com/nasa/dorado-scheduling` I get v 0.52 for skymap but v1.83 for python-ligo-lw. These are incompatible versions. Which versions should I use?

**Comment by mcoughlin** [comment]
@DanielWarshofsky Does the executable run anyways? The tiling doesn't depend on most of these.

**Comment by lpsinger** [comment]
I haven't updated this package in a while. I'll take a look at cleaning up the dependencies shortly.

**Comment by DanielWarshofsky** [comment]
> 

Running  the `dorado-scheduling-skygrid` executable produces the same error.

**Comment by mcoughlin** [comment]
And if you temporarily pip install ligo.skymap 0.61 or higher?

**Comment by DanielWarshofsky** [comment]
Updating ligo-skymap to 0.6.1 lets the executable run but gives a warning from pip 
`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
dorado-scheduling 0.1.0 requires ligo.skymap<0.6.0,>=0.5.2, but you have ligo-skymap 0.6.1 which is incompatible.`
Down grading python-ligo-lw to before v1.8 also works but Im unsure what side effects there might be between these versions.

**Comment by lpsinger** [comment]
What if you use `poetry install`? The locked dependency versions should still work.

**Comment by lpsinger** [comment]
Please try again now.

**Comment by DanielWarshofsky** [comment]
reinstalled via `pip install git+https://github.com/nasa/dorado-scheduling` and It works! Thanks!
