### ISSUE TITLE
CPLEX error in running the sample code

### ISSUE THREAD

**Issue by AkshayPanayada** [nasa/dorado-scheduling#88]
docplex.mp.utils.DOcplexLimitsExceeded: **** Promotional version. Problem size limits (1000 vars, 1000 consts) exceeded, model has 39825497 vars, 454925 consts, CPLEX code=1016

 am receiving this error after running the code in the cluster
Using 100GB ram

**Comment by mcoughlin** [comment]
@AkshayPanayada Please post the command line that triggered this issue.

**Comment by lpsinger** [comment]
You need to install a full version of CPLEX. See https://m4opt.readthedocs.io/en/latest/solvers.html#academic-users for instructions.

**Comment by AkshayPanayada** [comment]
I tried the same and ran the code again. Still got the same error

**Comment by AkshayPanayada** [comment]
@mcoughlin the sh file I used is given below

#!/bin/bash
#SBATCH -p shared
#SBATCH --job-name=test_dorado.job
#SBATCH --output=test_dorado_%A_%a.out
#SBATCH --error=test_dorado_%A_%a.err
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --gpus=0
#SBATCH -A umn131
#SBATCH --mem=100G
#SBATCH --time=01:30:00

dorado-scheduling  -o  new.ecsv /home/apanayada/Soft/dorado-scheduling/examples/6.fits

**Comment by lpsinger** [comment]
Fixed by https://github.com/m4opt/m4opt/pull/73.
