### ISSUE TITLE
NotImplementedError related to Orbit units when calling the scheduler with mission=uvex

### ISSUE THREAD

**Issue by criswellalexander** [nasa/dorado-scheduling#94]
Calling the scheduler with the following command:

> dorado-scheduling "${SKYMAP_DIR}/${num}.fits" -o "${SCHED_DIR}/${num}.ecsv" -j --mission=uvex --exptime="${texp} ks" --duration="${DURATION}" --roll-step='360 deg' --skygrid-method=sinusoidal --skygrid-step='10 deg2' --nside=128 --delay='10 yr'

where the bash variables for the fits file/ecsv file are correct absolute paths, $texp ranges from 0.5 to 10.8, and $DURATION is "3 hr",

yields a NotImplementedError:

> Traceback (most recent call last):
>   File "/home/vuk/crisw015/.conda/envs/uvex-followup-env/bin/dorado-scheduling", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/home/vuk/crisw015/.conda/envs/uvex-followup-env/lib/python3.11/site-packages/dorado/scheduling/scripts/main.py", line 128, in main
>     with u.add_enabled_equivalencies(equivalencies.orbital(mission.orbit)):
>                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/vuk/crisw015/.conda/envs/uvex-followup-env/lib/python3.11/site-packages/dorado/scheduling/units/equivalencies.py", line 14, in orbital
>     return Equivalency([(_orbit, orbit.period.unit,
>                                  ^^^^^^^^^^^^
>   File "/home/vuk/crisw015/.conda/envs/uvex-followup-env/lib/python3.11/site-packages/dorado/scheduling/orbit/base.py", line 19, in period
>     raise NotImplementedError
> NotImplementedError

**Comment by lpsinger** [comment]
Would you please attach the example sky map that you are using and provide a command line that does not contain any variables, so that I can try to reproduce this?

**Comment by lpsinger** [comment]
Confirmed. I'm working on it. Expect a fix later today.
